#! /bin/sh

set -e

case "$1" in
	configure)
		echo 'installing clock data...'
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	
	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 0
	;;
esac

exit 0

